name: Awesome CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Building project with Gradle
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/checkout@v2

        - name: Set up JDK 8
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'adopt'
        - name: Testing
          working-directory: .
          run: |
            chmod +x gradlew
            ./gradlew test
        - name: Run Test Coverage #generating jacocoTestReport
          run: ./gradlew jacocoTestReport

        - name: Generate JaCoCo Badge #generating a badge
          uses: cicirello/jacoco-badge-generator@v2
          with:
            generate-branches-badge: true
            jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

        - name: Commit and push the badge (if it changed) #commit and push the badge to github repo
          uses: EndBug/add-and-commit@v7
          with:
            default_author: github_actions
            message: 'Commit Coverage Badge'
            add: '*.svg'

        - name: Upload JaCoCo coverage report #upload the report
          uses: actions/upload-artifact@v2
          with:
            name: jacoco-report
            path: build/reports/jacoco
  
